apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: petclinic
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: petclinic
  endpoints:
    - port: 8080
      path: /actuator/prometheus
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
