apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
        release: kube-prometheus-stack
    spec:
      containers:
        - name: petclinic
          image: springcommunity/spring-petclinic-rest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: postgres
            - name: SPRING_APPLICATION_JSON
              value: |
                {
                  "spring.datasource.url": "jdbc:postgresql://postgres:5432/petclinic",
                  "spring.datasource.username": "postgres",
                  "spring.datasource.password": "password",
                  "management.endpoints.web.exposure.include": "health,prometheus,metrics",
                  "management.endpoint.prometheus.enabled": true
                }
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
  labels:
    app: petclinic
    release: kube-prometheus-stack
spec:
  selector:
    app: petclinic
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
