---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  selector:
    app: petclinic
  ports:
    - port: 8080
      targetPort: 8080
      name: http

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: petclinic-monitor
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: petclinic
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
